### ISSUE TITLE
Searching on PHP and HTML causes error

### ISSUE THREAD

**Issue by danrovito** [tzsk/scrape-pod#3]
## Detailed description

This issue is a bug.  When you search on `php` or `html`

```
$response = ScrapePod::search("php");
```
you get a return value of

```
"status" => false
"message" => "Undefined property: stdClass::$feedUrl"
```

This is happening in php 7.1 on windows 10.

**Comment by tzsk** [comment]
@danrovito Okay, I'll look into it. Please let me know if this issue happening in any other OS or PHP versions?

**Comment by tzsk** [comment]
@danrovito I ran several tests at my end and through Travis but still I couldn't replicate the issue. I am guessing maybe it's a CURL issue with your OpenSSL maybe. Which is failing the Response and the response returns null or something.

https://travis-ci.org/tzsk/scrape-pod/builds/299259765

**Comment by danrovito** [comment]
Thanks for looking at this for me.  I wasn't able to try it on any other OS or PHP Version. I'll see if it's my VM.
